Master:
  InstallPlugins:
    - branch-api:2.5.3
    - credentials:latest
    - credentials-binding:latest
    - git:latest
    - job-dsl:latest
    - kubernetes:latest
    - kubernetes-pipeline-steps:latest
    - workflow-job:2.15
    - workflow-aggregator:latest
rbac:
  install: true
  serviceAccountName: helm-jenkins
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: cluster-admin
