apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: aterefe/jenkins-sbt-docker:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false -Dpermissive-script-security.enabled=NO_SECURITY"
        volumeMounts:
        - name: ref-volume
          mountPath: /usr/share/jenkins/ref
        - name: ssh-volume
          mountPath: /var/jenkins_home/.ssh
        - name: sbt-volume
          mountPath: /var/jenkins_home/.sbt
        - name: docker-socket-volume
          mountPath: /var/run/docker.sock
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/usr/share/jenkins/ref/jenkins-k8s/scripts/wait-for-jenkins-and-run-job.sh meta-job"]
      initContainers:
      - name: clone-repo
        image: aterefe/jenkins-sbt-docker:latest
        command:
          - /bin/sh
          - -c
          - cp /etc/secret-volume/ssh-privatekey ~/.ssh/id_rsa;
            cp /etc/secret-volume/ssh-publickey ~/.ssh/id_rsa.pub;
            cp /etc/sbt-secret-volume/tmnow.credentials ~/.sbt/tmnow.credentials;
            cp /etc/docker-secret-volume/config.json ~/.docker/config.json;
            chmod 400 ~/.ssh/*;
            chmod 400 ~/.sbt/*;
            chmod 400 ~/.docker/*;
            printf "host github.com\n HostName github.com\n IdentityFile ~/.ssh/id_rsa\n User jenkins" > ~/.ssh/config;
            ssh-keyscan github.com >> ~/.ssh/known_hosts;
            cd /usr/share/jenkins/ref;
            git clone git@github.com:abelbryo/jenkins-k8s.git

        volumeMounts:
        - name: ref-volume
          mountPath: /usr/share/jenkins/ref
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
        - name: sbt-secret-volume
          mountPath: /etc/sbt-secret-volume
          readOnly: true
        - name: docker-secret-volume
          mountPath: /etc/docker-secret-volume
          readOnly: true
        - name: ssh-volume
          mountPath: /var/jenkins_home/.ssh
        - name: sbt-volume
          mountPath: /var/jenkins_home/.sbt
        - name: docker-config-volume
          mountPath: /var/jenkins_home/.docker
      - name: install-plugins
        image: aterefe/jenkins-sbt-docker:latest
        command:
          - /bin/sh
          - -c
          - install-plugins.sh < /usr/share/jenkins/ref/jenkins-k8s/plugins
        volumeMounts:
        - name: ref-volume
          mountPath: /usr/share/jenkins/ref
      - name: override-config
        image: aterefe/jenkins-sbt-docker:latest
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MASTER_URL
          valueFrom:
            configMapKeyRef:
              name: kube-master
              key: master.url
        command:
          - /bin/sh
          - -c
          - mkdir /usr/share/jenkins/ref/init.groovy.d;
            cp /usr/share/jenkins/ref/jenkins-k8s/overrides/* /usr/share/jenkins/ref/;
            cp /usr/share/jenkins/ref/jenkins-k8s/scripts/security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy;
            /usr/share/jenkins/ref/jenkins-k8s/scripts/hack-jenkins-env.sh;
        volumeMounts:
        - name: ref-volume
          mountPath: /usr/share/jenkins/ref
      - name: copy-jobs
        image: aterefe/jenkins-sbt-docker:latest
        command:
          - /bin/sh
          - -c
          - cp -r /usr/share/jenkins/ref/jenkins-k8s/jobs /usr/share/jenkins/ref/
        volumeMounts:
        - name: ref-volume
          mountPath: /usr/share/jenkins/ref
      volumes:
      - name: ref-volume
        emptyDir: {}
      - name: ssh-volume
        emptyDir: {}
      - name: sbt-volume
        emptyDir: {}
      - name: docker-config-volume
        emptyDir: {}
      - name: docker-socket-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: secret-volume
        secret:
          secretName: tmnow-ssh-secret
      - name: sbt-secret-volume
        secret:
          secretName: sbt-tmnow-jfrog-credentials
      - name: docker-secret-volume
        secret:
          secretName: docker-tmnow-jfrog-credentials


