apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - port: 5000
    nodePort: 30000
  externalTrafficPolicy: Cluster
